Repository fusionjs/fusion-plugin-react-router, pull requests merged in 2018-11, with the labels that each got.

#201 Implement flow fixes for 0.85
  package.json
  src/__tests__/plugin.js
  src/modules/BrowserRouter.js
  src/modules/Redirect.js
  src/modules/ServerHistory.js
  src/modules/ServerRouter.js
  src/plugin.js
  yarn.lock
Labels: bugfix, dependencies, greenkeeping

#202 Release v1.4.2-0
  package.json
Labels: release

#204 Release v1.4.2
  package.json
Labels: release

#205 Upgrade dependencies
  package.json
  yarn.lock
Labels: greenkeeping
