Repository fusionjs/fusion-plugin-react-router, pull requests merged in 2018-08, with the labels that each got.

#168 Expose history object in plugin API and token for overriding Router provider
  README.md
  src/__tests__/notfound.browser.js
  src/__tests__/notfound.node.js
  src/__tests__/plugin.js
  src/__tests__/redirect.browser.js
  src/__tests__/redirect.node.js
  src/__tests__/route.browser.js
  src/__tests__/route.node.js
  src/__tests__/status.browser.js
  src/__tests__/status.node.js
  src/__tests__/switch.browser.js
  src/__tests__/switch.node.js
  src/index.js
  src/modules/BrowserRouter.js
  src/modules/ServerHistory.js
  src/modules/ServerRouter.js
  src/plugin.js
  src/types.js
Labels: bugfix, feature

#169 Release v1.2.0-0
  package.json
Labels: release

#176 Update dependencies
  package.json
  yarn.lock
Labels: greenkeeping

#180 Use scoped emitter for server side events
  src/__tests__/plugin.js
  src/plugin.js
Labels: feature
