Repository fusionjs/fusion-plugin-react-router, pull requests merged in 2018-10, with the labels that each got.

#189 Upgrade dependency versions
  package.json
  yarn.lock
Labels: greenkeeping

#192 Release v1.5.0-0
  package.json
Labels: release

#198 Fix server redirects to include prefix
  src/__tests__/plugin.js
  src/modules/ServerHistory.js
  src/modules/utils.js
  src/plugin.js
Labels: bugfix

#197 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor

#200 Release v1.4.1
  package.json
Labels: release
